#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Stack: Next.js 15 + PostgreSQL via docker-compose.yml
# Match: multi-match (compose + react-next) → agent fallback (D-06)
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - Agent fallback because docker-compose.yml + next.config.mjs both matched
#     (compose entry + react-next entry) — D-05/D-06 multi-match → no mechanical merge.
#   - EXEC_CMD = `docker compose up --build`: compose owns DB health-gate → migrate
#     → seed → serve; the app's own `command:` in compose.yml handles ordering.
#     `--build` is load-bearing: pivota sandboxes modify source between boots;
#     a plain `up` reuses a stale cached image (observed crash-loop in ureport311
#     phase 4, 2026-07-13).
#   - No separate npm install in the wrapper: docker compose build / the
#     Dockerfile's `RUN npm ci` handles install inside the container image.
#     Installing on the host would be redundant and wrong for this stack.
#   - No LOCK_FILE sentinel for compose: docker manages its own layer cache;
#     there is no host-side node_modules to skip-install for.
#   - Log destination `/tmp/pivota-dev.log` — D-11.4 (always writable in Daytona
#     sandboxes; matches existing convention).
#   - Ready port 3000: declared in compose ports: "3000:3000"; app's dev script
#     explicitly binds 0.0.0.0:3000 via `next dev -H 0.0.0.0 -p 3000`.
#   - Single-process wrapper (not multi-process-template.md): `docker compose up`
#     is a single foreground process from the wrapper's perspective — compose
#     handles its own child orchestration (multi-process-template.md §6).
#   - sha256sum for lockfile hashing — RESEARCH.md "Don't hand-roll".
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Compose services control their own bind addresses via the `ports:` block in
# the compose file — there is no env-var lever the wrapper can pull to force
# 0.0.0.0 binding for child containers. The app service in docker-compose.yml
# runs `next dev -H 0.0.0.0 -p 3000` which already binds 0.0.0.0.
#
# HOSTNAME and HOST are exported here as well for any host-side tooling that
# reads them (compose itself ignores them; Next.js inside the container uses -H).
export HOSTNAME=0.0.0.0
export HOST=0.0.0.0

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. Any KEY already set in the environment is dropped from the copy
# so the injected value wins. See references/runtime-environment.md §3.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: sanitize the copied assignment — strip unquoted inline # comments.
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    # Replace CHANGE_ME / REPLACE_WITH placeholder secrets with generated values.
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* || "$value_lc" == replace_with* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === Pre-exec snippet: allowedDevOrigins overlay for Next.js sandbox preview ===
# Patch next.config.mjs to permit Daytona preview origin embedding in dev iframes.
# Only applied if the user's config does NOT already declare allowedDevOrigins.
for CFG in next.config.mjs next.config.js next.config.ts; do
  if [[ -f "$CFG" ]]; then
    if ! grep -q "allowedDevOrigins" "$CFG" 2>/dev/null; then
      mkdir -p .pivota
      cat > .pivota/next.config.pivota.cjs <<'OVERLAY_EOF'
// Auto-generated by pivota init-dev-server. Extends user's next.config to permit
// Daytona preview origin embedding in dev. Phase 39 will refine this; for now
// the overlay is a best-effort seed.
module.exports = (phase, { defaultConfig }) => {
  let user = {};
  try { user = require('../next.config.js'); }
  catch { try { user = require('../next.config.mjs').default || {}; } catch {} }
  if (typeof user === 'function') user = user(phase, { defaultConfig });
  return {
    ...user,
    allowedDevOrigins: [
      ...(user.allowedDevOrigins || []),
      '*.preview.daytona.io',
      '*.daytona.work',
    ],
  };
};
OVERLAY_EOF
      echo "[pivota] wrote .pivota/next.config.pivota.cjs (allowedDevOrigins overlay)"
    fi
    break
  fi
done

# === No host-side install step for compose stack ===
# The Dockerfile (`RUN npm ci`) handles dependency installation inside the
# container image. docker compose build caches layers; `--build` in EXEC_CMD
# only rebuilds changed layers. There is no lock file to sentinel on the host.

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='docker compose up --build'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
